In [1]:
import numpy as np

In [2]:
a=np.array([20,90,56,45,12,10])

In [3]:
a

array([20, 90, 56, 45, 12, 10])

In [4]:
np.mean(a)

38.833333333333336

In [5]:
p=np.mean(a)

In [6]:
p

38.833333333333336

In [7]:
round(p,2)

38.83

In [8]:
b=np.array([10,20,30,40,50,60,70])

In [9]:
b

array([10, 20, 30, 40, 50, 60, 70])

In [10]:
np.mean(b)

40.0

In [11]:
np.median(b)

40.0

In [12]:
a

array([20, 90, 56, 45, 12, 10])

In [13]:
a.min()

10

In [14]:
a.max()

90

In [15]:
range_of_a=a.max()-a.min()

In [16]:
range_of_a

80

In [17]:
a

array([20, 90, 56, 45, 12, 10])

In [18]:
a.var()

809.4722222222222

In [19]:
# stander deviation
a.std()

28.451225320225177

In [20]:
round(a.std(),2)

28.45

In [21]:
b

array([10, 20, 30, 40, 50, 60, 70])

In [24]:
b.var()

400.0

In [25]:
b.std()

20.0

In [27]:
import pandas as pd
df=pd.read_csv("student_marks.csv")
df.head()

Name Gender         DOB  Maths  Physics  Chemistry  English  Biology  \
0      John      M  05-04-1988     55       45         56       87       21   
1    Suresh      M  04-05-1987     75       96         78       64       90   
2    Ramesh      M  25-05-1989     25       54         89       76       95   
3   Jessica      F  12-08-1990     78       96         86       63       54   
4  Jennifer      F  02-09-1989     58       96         78       46       96   

   Economics  History  Civics  
0         52       89      65  
1         61       58       2  
2         87       56      74  
3         89       75      45  
4         77       83      53

In [29]:
df['Maths'].mean()

59.6

In [31]:
df['English'].mean()

69.7

In [32]:
df['Chemistry'].mean()

75.3

In [33]:
df['Maths'].median()

55.0

In [34]:
df['Maths'].mode()

0    55
Name: Maths, dtype: int64

In [36]:
df['Physics'].mode()

0    96
Name: Physics, dtype: int64

In [37]:
df.describe()

Maths    Physics  Chemistry    English    Biology  Economics  \
count  10.000000  10.000000  10.000000  10.000000  10.000000  10.000000   
mean   59.600000  72.300000  75.300000  69.700000  64.700000  72.700000   
std    19.460501  20.661559  14.000397  14.453373  26.998148  14.629119   
min    25.000000  45.000000  52.000000  46.000000  21.000000  52.000000   
25%    54.250000  56.250000  65.000000  59.250000  54.250000  58.750000   
50%    55.000000  70.000000  78.000000  69.500000  66.500000  76.000000   
75%    70.750000  93.750000  86.750000  81.250000  87.000000  86.000000   
max    96.000000  96.000000  89.000000  89.000000  96.000000  89.000000   

         History   Civics  
count  10.000000  10.0000  
mean   69.700000  60.5000  
std    14.453373  25.3432  
min    46.000000   2.0000  
25%    59.250000  52.2500  
50%    69.500000  63.0000  
75%    81.250000  76.2500  
max    89.000000  89.0000